import { useEffect, useLayoutEffect, useRef, useState, useId, type ReactNode, type RefObject } from "react";
import { createPortal } from "react-dom";
import { AlignLeft, AlignCenter, AlignRight, AlignJustify, ChevronDown, Highlighter, IndentDecrease, IndentIncrease, Paintbrush, Eraser, Pilcrow, Check } from "lucide-react";
import type { NoteMarkdownEditorHandle } from "./note-markdown-editor";
import type { NoteEditorFormat } from "./note-editor-format";
export function WritingPopover({ label, children, disabled, trigger, onClose, className = "" }: { label: string; trigger: ReactNode; children: (close: () => void) => ReactNode; disabled?: boolean; onClose?: () => void; className?: string }) {
  const [open, setOpen] = useState(false), button = useRef<HTMLButtonElement>(null), panel = useRef<HTMLDivElement>(null), keyboardOpen = useRef(false);
  const close = () => { setOpen(false); onClose?.(); };
  useLayoutEffect(() => { if (!open || !panel.current || !button.current) return;
    const place = () => { const bounds = button.current!.getBoundingClientRect(), popup = panel.current!; popup.style.left = `${Math.max(12, Math.min(bounds.left, window.innerWidth - popup.offsetWidth - 12))}px`; popup.style.top = `${bounds.bottom + popup.offsetHeight + 8 < window.innerHeight ? bounds.bottom + 8 : Math.max(12, bounds.top - popup.offsetHeight - 8)}px`; };
    panel.current.showPopover?.(); place(); if (keyboardOpen.current) panel.current.querySelector<HTMLButtonElement>("button:not(:disabled)")?.focus(); window.addEventListener("resize", place); document.addEventListener("scroll", place, true);
    return () => { window.removeEventListener("resize", place); document.removeEventListener("scroll", place, true); };
  }, [open]);
  useEffect(() => { if (!open) return;
    const outside = (event: PointerEvent) => { if (!panel.current?.contains(event.target as Node) && !button.current?.contains(event.target as Node)) setOpen(false); };
    const escape = (event: KeyboardEvent) => { if (event.key !== "Escape" || event.isComposing) return; event.preventDefault(); event.stopPropagation(); close(); if (!onClose) button.current?.focus(); };
    document.addEventListener("pointerdown", outside, true); document.addEventListener("keydown", escape, true);
    return () => { document.removeEventListener("pointerdown", outside, true); document.removeEventListener("keydown", escape, true); };
  }, [open]);
  return <><button ref={button} type="button" className="writing-control-trigger" disabled={disabled} aria-label={label} aria-expanded={open} aria-haspopup="dialog" onMouseDown={event => event.preventDefault()} onKeyDown={event => { if (event.key === "ArrowDown") { event.preventDefault(); keyboardOpen.current = true; setOpen(true); } }} onClick={event => { keyboardOpen.current = event.detail === 0; setOpen(!open); }}>{trigger}<ChevronDown size={12} /></button>
    {open ? createPortal(<div ref={panel} className={`note-format-popup ${className}`} popover="manual" role="dialog" aria-label={label} onKeyDown={event => { if (!(event.target instanceof HTMLButtonElement) || !["ArrowDown", "ArrowUp", "ArrowRight", "ArrowLeft", "Home", "End"].includes(event.key)) return; const choices = [...panel.current!.querySelectorAll<HTMLButtonElement>("button:not(:disabled)")], at = choices.indexOf(event.target); event.preventDefault(); const next = event.key === "Home" ? 0 : event.key === "End" ? choices.length - 1 : (at + (["ArrowDown", "ArrowRight"].includes(event.key) ? 1 : -1) + choices.length) % choices.length; choices[next]?.focus(); }}><div className="note-format-popup__caption">{label}</div>{children(close)}</div>, document.body) : null}</>;
}
export function NotebookBlockFormat({ heading, editable, editorRef }: { heading: number; editable: boolean; editorRef: RefObject<NoteMarkdownEditorHandle | null> }) {
  return <WritingPopover label="段落格式" disabled={!editable} trigger={<span>{heading ? `标题 ${heading}` : "正文"}</span>} onClose={() => editorRef.current?.focus()}>{close => <div className="writing-heading-list">{[0,1,2,3,4,5,6].map(level => <button type="button" key={level} aria-pressed={heading === level} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.toggleHeading(level); close(); }}><span className="writing-heading-list__symbol">{level ? `H${level}` : "¶"}</span><span style={{ fontSize: level ? 23 - level * 2 : 14 }}>{level ? `标题 ${level}` : "正文段落"}</span>{heading === level ? <Check size={14} /> : null}</button>)}</div>}</WritingPopover>;
}
const colors = ["#403629", "#746a5d", "#a44b3b", "#c18134", "#8c7c32", "#517451", "#427a82", "#4d6595", "#795d91", "#a35f79", "#ddddcc", "#ffffff"];
export function NotebookFormatControls({ editorRef, editable, format, actions = true, compact = false }: { editorRef: RefObject<NoteMarkdownEditorHandle | null>; editable: boolean; format: NoteEditorFormat | null; actions?: boolean; compact?: boolean }) {
  const colorId = useId();
  const [hex, setHex] = useState("#403629"), text = format?.textStyle, paragraph = format?.paragraphStyle;
  const focus = () => editorRef.current?.focus();
  const fontNames = { serif: "衬线", sans: "无衬线", mono: "等宽" };
  return <div className="writing-format-group" aria-label="文字与段落格式">
    <WritingPopover label="文字字体" disabled={!editable} trigger={<span>{text?.font ? fontNames[text.font] : "字体"}</span>} onClose={focus}>{close => <div className="writing-font-list">{(["serif", "sans", "mono"] as const).map(font => <button key={font} type="button" aria-pressed={text?.font === font} style={{ fontFamily: { serif: "serif", sans: "sans-serif", mono: "monospace" }[font] }} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.setTextStyle?.({ font }); close(); }}><span>{fontNames[font]}</span><span className="writing-font-sample">拾星 · 写下理解 Aa</span>{text?.font === font ? <Check size={14} /> : null}</button>)}</div>}</WritingPopover>
    <WritingPopover label="文字字号" disabled={!editable} trigger={<span>{text?.size ?? "字号"}</span>} onClose={focus}>{close => <div className="writing-size-grid">{[12,14,16,18,20,24,28,32,40,48].map(size => <button type="button" key={size} aria-pressed={text?.size === size} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.setTextStyle?.({ size }); close(); }}>{size}</button>)}</div>}</WritingPopover>
    <WritingPopover label="文字颜色" disabled={!editable} trigger={<span className="writing-color-symbol" style={{ borderColor: text?.color ?? hex }}>A</span>} onClose={focus}>{close => <><div className="writing-color-palette">{colors.map(color => <button key={color} type="button" aria-label={`颜色 ${color}`} aria-pressed={text?.color === color} style={{ background: color }} onMouseDown={event => event.preventDefault()} onClick={() => { setHex(color); editorRef.current?.setTextStyle?.({ color }); close(); }}>{text?.color === color ? <Check size={13} /> : null}</button>)}</div><form className="writing-color-custom" onSubmit={event => { event.preventDefault(); if (/^#[a-f0-9]{6}$/i.test(hex)) { editorRef.current?.setTextStyle?.({ color: hex }); close(); } }}><label htmlFor={colorId}>自定颜色</label><input id={colorId} aria-label="十六进制文字颜色" value={hex} maxLength={7} onChange={event => setHex(event.target.value)} /><button type="submit">应用</button></form></>}</WritingPopover>
    {!compact ? <button type="button" className="tool" aria-label="文本高亮" aria-pressed={Boolean(format?.highlight)} disabled={!editable} title="高亮文字" onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.toggleExtension?.("highlight"); focus(); }}><Highlighter size={16} /></button> : null}
    <span className="writing-format-group__divider" />
    <WritingPopover label="段落排版" disabled={!editable} trigger={<><Pilcrow size={15} /><span>段落</span></>} onClose={focus}>{close => <><div className="writing-alignment-choices">{([["left", AlignLeft, "左对齐"], ["center", AlignCenter, "居中对齐"], ["right", AlignRight, "右对齐"], ["justify", AlignJustify, "两端对齐"]] as const).map(([align, Icon, label]) => <button key={align} type="button" aria-label={label} aria-pressed={(paragraph?.align ?? "left") === align} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.setParagraphStyle?.({ align }); close(); }}><Icon size={20} /><span>{label}</span></button>)}</div><div className="note-format-popup__caption">行距</div><div className="writing-leading-choices">{[1.2,1.5,1.8,2,2.4,3].map(leading => <button key={leading} type="button" aria-label={`行距 ${leading}`} aria-pressed={paragraph?.leading === leading} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.setParagraphStyle?.({ leading }); close(); }}>{leading}</button>)}</div></>}</WritingPopover>
    {actions ? <NotebookFormatActions editorRef={editorRef} editable={editable} format={format} /> : null}
  </div>;
}

/** Advanced commands can live in the overflow page without nesting another popover. */
export function NotebookFormatActions({ editorRef, editable, format, labels = false, onDone }: { editorRef: RefObject<NoteMarkdownEditorHandle | null>; editable: boolean; format: NoteEditorFormat | null; labels?: boolean; onDone?: () => void }) {
  const focus = () => { onDone?.(); editorRef.current?.focus(); };
  return <>
    {([[-1, IndentDecrease, "减少缩进"], [1, IndentIncrease, "增加缩进"]] as const).map(([indent, Icon, label]) => <button key={label} type="button" className="tool" disabled={!editable} aria-label={label} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.setParagraphStyle?.({ indent }); focus(); }}><Icon size={16} />{labels ? <span>{label}</span> : null}</button>)}
    <button type="button" className="tool" disabled={!editable || format?.source} aria-label="格式刷" aria-pressed={Boolean(format?.brush)} title={format?.source ? "在排版正文中使用格式刷" : "取当前格式，再选择文字；Esc 取消"} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.formatBrush?.(); focus(); }}><Paintbrush size={16} />{labels ? <span>格式刷</span> : null}</button>
    <button type="button" className="tool" disabled={!editable || format?.source} aria-label="清除格式" title={format?.source ? "在排版正文中清除格式" : "清除所选文字和段落格式"} onMouseDown={event => event.preventDefault()} onClick={() => { editorRef.current?.clearFormat?.(); focus(); }}><Eraser size={16} />{labels ? <span>清除格式</span> : null}</button>
    {format?.brush ? <span className="writing-brush-hint" role="status">选取文字套用格式 · Esc 取消</span> : null}
  </>;
}
